### ISSUE TITLE
"Invalid flag for command"

### ISSUE THREAD

**Issue by esnible** [CycloneDX/sbom-utility#34]
When I invoke `sbom-utility validate --input-file` I always see the following warning:

```
[WARN] Invalid flag for command: `output-file` (`o`). Ignoring...
```

**Comment by mrutkows** [comment]
@esnible I will take a look at this before the next release.

**Comment by mrutkows** [comment]
This was a copy/paste error when trying to add command pre-reqs that were added on other commands
