### ISSUE TITLE
JSON output format for SBOM validation

### ISSUE THREAD

**Issue by MathewsSaiji1** [CycloneDX/sbom-utility#36]
Currently the output is directly outputted to the terminal directly.
But if you can format the output in a json format ,it would be easy to identify the error and act according to every error cases.
If the sbom-utility cannot support any specific version ,we just want to warn the user that the SBOM validity scan is not supported.But if its an error in SBOM itself, we need to consider it as an issue.

A Sample:

> validation : (true/false/not_supported)
> Description : [no error/json format error/ schema error]
> errorlist:
>     [ {
>        type : <>
>        description : <>
>         feild : <>
>        },
>    {
>        type : <>
>        description : <>
>         feild : <>
>        }]

It is just an example.Feel free to change the variables,format or even the whole structure as per the requirement.But it would be easy if you provide an efficient way to capture the result.

**Comment by mrutkows** [comment]
@MathewsSaiji1 Thanks for submitting this feature request. I will see if I have time to work on this for the next release.

**Comment by MathewsSaiji1** [comment]
Sure,happy to share my thoughts

From: Matt Rutkowski ***@***.***>
Date: Wednesday, 7 June 2023 at 7:59 PM
To: CycloneDX/sbom-utility ***@***.***>
Cc: Mathews Saiji1 ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [CycloneDX/sbom-utility] JSON output format for SBOM validation (Issue #36)
@MathewsSaiji1 Thanks for submitting this feature request. I will see if I have time to work on this for the next release. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

@MathewsSaiji1<https://github.com/MathewsSaiji1> Thanks for submitting this feature request. I will see if I have time to work on this for the next release.
