### ISSUE TITLE
Include config.json and licenses.json in the compiled executable

### ISSUE THREAD

**Issue by garethr** [CycloneDX/sbom-utility#46]
It's unusual I feel to require config files on disk that are _mainly_ going to be the same for all users. Has there been consideration of compiling that data into the executable, and then allowing it to be overridden by those users that want to do so?

**Comment by mrutkows** [comment]
@garethr I had considered including all the .json config files in the built-in resources for some time; very happy to encounter a security-minded developer who is not afraid to customize those files and re-build.  This should be easier as there is a single "load" function which prioritizes where to load from and would hopefully simply just need to attempt to load it from resources first then continue along the current logic of not found.

**Comment by mrutkows** [comment]
@garethr Merged the code for this; feel free to give it a try in advance of the next point release.  Am on vacation this week, during which I hope to address the other issue you opened as it something I have thought of doing for some time.
