### ISSUE TITLE
Release v013.0 is missing release assets

### ISSUE THREAD

**Issue by nicholasdille** [CycloneDX/sbom-utility#58]
The workflow for release v0.13.0 has failed and no release assets have been published.

**Comment by mrutkows** [comment]
@nicholasdille Hi Nicholas, I saw the same thing, but not until the next morning... I believe that upon regeneration of the release that all assets were created (still unsure of the initial failure).   Do you see the same?

**Comment by nicholasdille** [comment]
No worries. My work flow picked up the release assets and published them. Tha KS for getting back to me 😊
